on:
  pull_request:

jobs:
  build-base:
    name: 'Build base'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.base_ref }}
    - name: Install dependencies
      run: npm ci
    - name: Generate bundle stats
      run: npm run bundle:stats --if-present
    - name: Upload stats.json
      uses: actions/upload-artifact@v1
      with:
        name: base-stats
        path: ./dist/stats.json

  compare:
    name: 'Compare base & head bundle sizes'
    runs-on: ubuntu-latest
    needs: [build-base]
    steps:
    - uses: actions/checkout@v1
    - name: Download base artifact
      uses: actions/download-artifact@v1
      with:
        name: base-stats
    - name: Install dependencies
      run: npm ci
    - name: Generate bundle stats
      run: npm run bundle:stats
    - name: Diff between base & head
      run: npm run bundle:diff
      env:
        gitToken: ${{ secrets.GITHUB_TOKEN }}
        baseStatsPath: ./base-stats/stats.json
        headStatsPath: ./dist/stats.json