name: Create JIRA tickets

on:
  issues:
    types: [opened]

jobs:
  create_ticket_from_issue:
    name: Create JIRA ticket
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: DRV
          issuetype: Bug
          summary: "GITHUB ISSUE #${{github.event.issue.number}} ${{github.event.issue.title}}"
          description: "${{github.event.issue.url}} \n\n ${{github.event.issue.body}}"
          fields: '{"labels": ["github"], "components": [{ "name": "JavaScript Driver" }]}'

      - name: Set triage state
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.create.outputs.issue }}
          transition: "TRIAGE"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 1
          body: Internal ticket number is ${{steps.create.outputs.issue}}

      - name: Created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"
