name: Create JIRA ticket for GH pull request

on:
  pull_request:
    types: [opened]

jobs:
  create_ticket_from_pr:
    name: Create JIRA ticket
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: FE
          issuetype: Task
          summary: Pull Request ${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}
          description: ${{ github.event.pull_request.html_url }}
          fields: '{"labels": ["github", "pr", "dx-ops"], "components": [{ "name": "V4 JavaScript Driver" }]}'

      - name: Complete
        if: ${{ steps.create.outputs.issue }}
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"
